#生产环境配置
server:
  #端口
  port: 8080
spring:
  config:
    activate:
      on-profile: pro
  #redis配置
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:      # 密码（默认为空）
      timeout: 6000  # 连接超时时长（毫秒）
      lettuce:
        pool:
          enabled: true        # 需要添加此配置
          max-idle: 1000
          max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 5       # 连接池中的最小空闲连接
  # 数据源配置
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mysiteforme?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: mysiteforme
      password: rYhkf3riLyaAGsMR

#日志
logging:
  config: classpath:log/logback.xml
  file:
    path: /home/log/mysiteforme
  level:
    root: INFO
    org.springframework: INFO
